# Generated by Django 5.2.17 on 2026-09-13 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('face_photo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('average_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('visa', 'Visa')], max_length=50)),
                ('id_number', models.CharField(max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
                ('qr_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.verifieduser')),
            ],
        ),
    ]
