# Generated by Django 6.1.1 on 2026-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_thumbnail', models.TextField(blank=True, null=True)),
                ('back_thumbnail', models.TextField(blank=True, null=True)),
                ('ekyc_verified', models.BooleanField(default=False)),
                ('result', models.JSONField(default=dict)),
                ('extracted_fields', models.JSONField(default=dict)),
                ('saved_paths', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
